// queues a regeneration of the mp grid NOTE: If we don't change rooms, and so the grid size stays the same,
// then we probably just want to clear the grid and then use mp_grid_add_instances. We'll have to call
// initialise again when we change rooms...
