// Shieldbash config
#macro SHIELDBASH_DASH_SPEED_MULTIPLIER 3
#macro SHIELDBASH_DASH_STEPS 6

#macro SHIELDBASH_DASH_SLOW_MULTIPLIER 0.25
#macro SHIELDBASH_DASH_SLOW_STEPS 10

#macro SHIELDBASH_RANGE 20
#macro SHIELDBASH_DAMAGE 50